name: Update Wakatime Image

on:
  schedule:
    - cron: "0 */12 * * *" # run every 12 hours
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run
        run: go run .

      - name: Add File
        run: |
          git config --local user.email "belummikir@gmail.com"
          git config --local user.name "zakiego"
          git add .

      - name: Check is need to push
        id: check_status
        run: |
          STATUS=$(git status --porcelain | wc -l)
          echo "number of files that need to be committed:" $STATUS
          echo "::set-output name=STATUS::$STATUS"

      - name: Commit File
        if: steps.check_status.outputs.STATUS > 0
        run: |
          echo "status"
          now=$(date)
          git commit -m "feat: update wakatime"

      - name: Push Changes
        if: steps.check_status.outputs.STATUS > 0
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
